server:
  port: 8181
spring:
  application:
    name: test_app
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVER}
      group-id: test_group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl=${SSL_PATH}
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect:  org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: local

---
spring:
  profiles: nonlocal
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USER_NAME}' password='${KAFKA_PASSWORD}';
